language: java
dist: trusty
jdk:
  - oraclejdk8
install: mvn -B install -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
script: mvn -B package -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
before_deploy:
- echo "deploying odps console to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: cG67shSjDuQWaPbNnsnmcbFUrtrz/vf6SeW010kNYYYDSds92d6kcFEUvG1iXPyY7T0oJy1jdGqNiI80bvAkCzB3WUCYJTcJJDKDfRSBcpjeuNETNkCkvYWxwE/EIT7fCH4/ul/f0H65/2TgRvkIoEOnLV1YgyTpZKZQ1mS44N/H9dRo1VjQCvZLwLPcm6pSRsfhoOBQMJibf7BmbCuKZvYmgn9yD0x0gmpZC/HNV9fq0j8sIKcOGWKyBXcpVUC1J8LNJbFJzYLUkEbaqHPVB+8ruJKqHEehJOBqMN2Hn3rZ3iFQsr1Ogtylo1MwZj1txhCEkWynmjV1ms4/FhS0eYTnoaMSR49jSLHH0OhflY8FSurSul9GLj7e1PhLY3MopIPnXrwVDzamH+c5WNc93BYyD6rTXwXEWZVAa4abu8j1XJ4HI/6GztjDwNB5cYDD1/OE48iVdnHGztbDFvjT6wRGhozZMnGXjbk8/kHu3byhTQDlNximbAo1erZA894tacw1c/6z7TVO3oSkPooHNLUVVPuStzlniBO2Qp7c0P0xac7MLyfvcyp124zFkkmG+Z8hZRK7DdB94XZJ5Ia/rnTmThW7+/FVoO/kxo6dpgtYHE1y09gfX508lZ//+aWWubrRWXSQgITwG24cS68SBa7PNnZSYPpKHJ1vhhaNcps=
  file_glob: false
  file: odps-console-dist-public/target/odpscmd_public.zip
  skip_cleanup: true
  on:
    tags: true
    repo: aliyun/aliyun-odps-console
